SCR_MissionHeaderCombatOps {
 World "{9C985D8D499B31B8}worlds/Zimni_MCM_02.ent"
 m_sName "Zimnitrita - US vs RUS - Kromzova"
 m_sAuthor "tanin69"
 m_sDescription "COOP Game - Neutralize a russian FOB"
 m_sDetails "3 objectives : clear area, destroy a radar, destroy a supply truck. Heavy russian defence."
 m_sIcon "{2318D161D2699F4C}MissionLoadingScreens/Loading_Screen_2.edds"
 m_sLoadingScreen "{63AA69DBAF244A75}MissionLoadingScreens/Loading_Screen_1.edds"
 m_sPreviewImage "{A17FAC7DE1F017B3}MissionLoadingScreens/Loading_Screen_3.edds"
 m_iPlayerCount 22
 m_sSaveFileName "Zimmnitrita_MCM_Custom_02"
 m_sBriefingConfig "{5FC90A7F85BFDC7D}Configs/Journal/Journal_02_USvsRUS_Krozmova.conf"
 m_bOverrideScenarioTimeAndWeather 1
 m_bRandomStartingDaytime 1
 m_bRandomStartingWeather 1
 m_bRandomWeatherChanges 1
}