SCR_MissionHeaderCombatOps {
 World "{0586E414547C0028}worlds/Zimni_MCM_01.ent"
 m_sName "Zimnitrita - US vs RUS - Main Military Airport"
 m_sAuthor "tanin69"
 m_sDescription "COOP Game - The USMC must prevent the Russians from gaining a lasting foothold at the Zimnitrita military airport. Vehicle destruction and HVT elimination. "
 m_sDetails "The USMC must prevent the Russians from gaining a lasting foothold at the Zimnitrita military airport. Vehicle destruction and HVT elimination. "
 m_sIcon "{2318D161D2699F4C}MissionLoadingScreens/Loading_Screen_2.edds"
 m_sLoadingScreen "{63AA69DBAF244A75}MissionLoadingScreens/Loading_Screen_1.edds"
 m_sPreviewImage "{A17FAC7DE1F017B3}MissionLoadingScreens/Loading_Screen_3.edds"
 m_iPlayerCount 22
 m_sSaveFileName "Zimmnitrita_MCM_Custom_01"
 m_sBriefingConfig "{CA9C49AC1AB434F6}Configs/Journal/Journal_01_USvsRUS_MilitaryAirport.conf"
 m_bOverrideScenarioTimeAndWeather 1
 m_bRandomStartingDaytime 1
 m_bRandomStartingWeather 1
 m_bRandomWeatherChanges 1
}