SCR_JournalSetupConfig {
 m_iJournalEntryToShowOnStart 0
 m_aJournals {
  SCR_JournalConfig "{64FB41EB2CE50BD2}" {
   m_FactionKey "RHS_USAF"
   m_aEntries {
    SCR_JournalEntry "{64FB41EB2CE50BD7}" {
     m_iEntryID 1
     m_sCustomEntryName "#AR-RespawnMap_FRAGO_SituationTitle"
     m_sEntryText "Commander, the Russians have gained a foothold at Zimnitrita military airport.<br /><br />If we don't put the brakes on their deployment right away, they risk extending their advantage and rapidly consolidating their bridgehead."
    }
    SCR_JournalEntry "{64FB41EB2CE50BD9}" {
     m_iEntryID 2
     m_eJournalEntryType Mission
     m_sCustomEntryName "#AR-RespawnMap_FRAGO_MissionTitle"
     m_sEntryText "You must destroy the Mi8 in the airport hangars.<br /><br />If possible, also neutralize the main officer who has taken up residence in the HQ."
    }
    SCR_JournalEntry "{64FB41EB2CE50BDB}" {
     m_iEntryID 3
     m_eJournalEntryType Execution
     m_sCustomEntryName "#AR-RespawnMap_FRAGO_ExecutionTitle"
     m_sEntryText "You have carte blanche to carry out your mission. Or, to put it in words you'll understand better: figure it out for yourself !"
    }
    SCR_JournalEntry "{64FB41EB2CE5F809}" {
     m_iEntryID 4
     m_eJournalEntryType Signal
     m_sCustomEntryName "#AR-RespawnMap_FRAGO_SignalTitle"
     m_sEntryText "#AR-Briefing_CO_Arland_Signal_US"
    }
    SCR_JournalEntry "{64FB41EB2CE5F80F}" {
     m_iEntryID 5
     m_eJournalEntryType Intel
     m_sCustomEntryName "#AR-RespawnMap_FRAGO_IntelTitle"
     m_sEntryText "**Armed Vehicles**"\
     "Several Ilyushin Il-76 rotations have been noted. We therefore have a good chance of assuming that numerous BTR-70s have been deployed."\
     ""\
     "Worse: there are probably a few K-17 \"Boomerangs\" in the area."\
     ""\
     "**Infantry**"\
     "The hostiles are very well equipped and trained. In most areas, we can expect QRFs."
    }
   }
  }
 }
}