SCR_JournalSetupConfig {
 m_iJournalEntryToShowOnStart 0
 m_aJournals {
  SCR_JournalConfig "{6620E33BCD4ACD9A}" {
   m_FactionKey "RHS_USAF"
   m_aEntries {
    SCR_JournalEntry "{6620E33BCD4ACD9F}" {
     m_iEntryID 1
     m_sCustomEntryName "#AR-RespawnMap_FRAGO_SituationTitle"
     m_sEntryText "The Russians landed on the northern coast of Zimnitrita and took up positions near Kromzova. They set up an advance base outside the village and are controlling it."
    }
    SCR_JournalEntry "{6620E33BCD4ACC61}" {
     m_iEntryID 2
     m_eJournalEntryType Mission
     m_sCustomEntryName "#AR-RespawnMap_FRAGO_MissionTitle"
     m_sEntryText "- Cut off russian communications<br />- Destroy fuel supply capabilities<br />- Eliminate troops within the perimeter of the base camp."
    }
    SCR_JournalEntry "{6620E33BCD4ACC63}" {
     m_iEntryID 3
     m_eJournalEntryType Execution
     m_sCustomEntryName "#AR-RespawnMap_FRAGO_ExecutionTitle"
     m_sEntryText "The M997 ambulance will be your mobile redeployment point.<br />Once your objectives are completed, simply hold position (end mission).<br /><br /> You can complete the objectives in any order you choose. But beware, you are greatly outnumbered."
    }
    SCR_JournalEntry "{6620E33BCD4ACC64}" {
     m_iEntryID 4
     m_eJournalEntryType Signal
     m_sCustomEntryName "#AR-RespawnMap_FRAGO_SignalTitle"
     m_sEntryText "#AR-Briefing_CO_Arland_Signal_US"
    }
    SCR_JournalEntry "{6620E33BCD4A7C84}" {
     m_iEntryID 5
     m_eJournalEntryType Intel
     m_sCustomEntryName "#AR-RespawnMap_FRAGO_IntelTitle"
     m_sEntryText "**Armed Vehicles**<br />A few BTR-70s have been deployed.<br /><br />**Infantry**<br />The hostiles are very well equipped and trained. Expect some QRFs.<br /><br />All other intels are indicated on the map."
    }
   }
  }
 }
}