SCR_MissionHeader {
 World "{B0031E36C98E23DB}worlds/tanin69/Easy_Csorgy.ent"
 m_sName "COOP (15-30) - Easy Csorgy"
 m_sAuthor "tanin69"
 m_sDescription "Assaut mécanisé (Strykers) contre une compagnie mécanisée russe"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sLoadingScreen "{E7E47A3C70B073B6}UI/MissionLoadingScreens/easy_csorgy_loading_screen.edds"
 m_sGameMode "#AR-ServerBrower_ServerScenario"
 m_iPlayerCount 30
 m_iMapMarkerLimitPerPlayer 20
}