SCR_MissionHeader {
 World "{18ADBFA55C2416DE}worlds/tanin69/GulfCoast_mission01.ent"
 m_sName "COOP (15-24) - Baie des pochons I"
 m_sAuthor "tanin69"
 m_sDescription "Défense de zone - Soyez souples sur les pattes arrières !"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sLoadingScreen "{FD88F7ED25F37D1B}UI/MissionLoadingScreens/BTR-70-firing_FIA.edds"
 m_sGameMode "#AR-ServerBrower_ServerScenario"
 m_iPlayerCount 24
 m_iMapMarkerLimitPerPlayer 20
}