SCR_MissionHeader {
 World "{8674FC6D27459D8D}worlds/tanin69/GulfCoast_mission05.ent"
 m_sName "COOP (15-27) - Baie des pochons V"
 m_sAuthor "tanin69"
 m_sDescription "Trouvage et pétage d'une putain de batterie de mortiers dans la profondeur"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sLoadingScreen "{2CE98B0A518A5589}UI/MissionLoadingScreens/mortar_ussr_3.edds"
 m_sGameMode "#AR-ServerBrower_ServerScenario"
 m_iPlayerCount 27
 m_iMapMarkerLimitPerPlayer 20
}