SCR_MissionHeader {
 World "{1F6A45F43AA2AC1D}worlds/tanin69/GulfCoast_mission06.ent"
 m_sName "COOP (15-26) - Baie des pochons VI"
 m_sAuthor "tanin69"
 m_sDescription "Prise d'un aéroport avec soutien aérien"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sLoadingScreen "{9074096D4EF401B9}UI/MissionLoadingScreens/huey_1.edds"
 m_sGameMode "#AR-ServerBrower_ServerScenario"
 m_iPlayerCount 26
 m_iMapMarkerLimitPerPlayer 20
}