SCR_MissionHeader {
 World "{F17E94E5D3E772FD}worlds/tanin69/GulfCoast_mission04.ent"
 m_sName "COOP (15-27) - Baie des pochons IV"
 m_sAuthor "tanin69"
 m_sDescription "Reprise d'une base fortifiée attaquée par des spetsnaz"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sLoadingScreen "{373274AEBDCEF611}UI/MissionLoadingScreens/BTR-70-detruit.edds"
 m_sGameMode "#AR-ServerBrower_ServerScenario"
 m_iPlayerCount 27
 m_iMapMarkerLimitPerPlayer 20
}