SCR_MissionHeader {
 World "{F6B96EB4B561C83E}worlds/tanin69/GulfCoast_mission03.ent"
 m_sName "COOP (15-27) - Baie des pochons III"
 m_sAuthor "tanin69"
 m_sDescription "Destruction de moyens anti-aériens avec appui d'un LAV-25"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sLoadingScreen "{FD88F7ED25F37D1B}UI/MissionLoadingScreens/BTR-70-firing_FIA.edds"
 m_sGameMode "#AR-ServerBrower_ServerScenario"
 m_iPlayerCount 27
 m_iMapMarkerLimitPerPlayer 20
}