SCR_MissionHeader {
 World "{AB71CF070D457684}worlds/tanin69/Liberate_ZFR_2_Fish_Trap.ent"
 m_sName "COOP [8-12] - Fish Trap (la nasse)"
 m_sAuthor "tanin69"
 m_sDescription "Se sortir d'un merdier noir et rejoindre un point d'exfiltration"
 m_sIcon "{030E2E704B1974C2}UI/Textures/EditorPreviews/Characters/OPFOR/USSR_Army/Character_USSR_GL.edds"
 m_sLoadingScreen "{981489C7B8E7BF1C}UI/MissionLoadingScreens/FIA_Camp.edds"
 m_sGameMode "#AR-ServerBrower_ServerScenario"
 m_iPlayerCount 12
}