SCR_MissionHeader {
 World "{E6C3A33A56394BF8}worlds/tanin69/Liberate_ZPR_4_Vol_Coucou.ent"
 m_sName "COOP (15-30) - Vol au dessus d'un nid de coucou"
 m_sAuthor "tanin69"
 m_sDescription "Nettoyer une zone hostile avec appui d'un Mi-8"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sLoadingScreen "{A539259D33B8ED82}UI/MissionLoadingScreens/Loading_screen_Mission-03.edds"
 m_sGameMode "#AR-ServerBrower_ServerScenario"
 m_iPlayerCount 29
}