SCR_MissionHeader {
 World "{D21EB16DDA352778}worlds/tanin69/Liberate_ZFR_1_Sabotage.ent"
 m_sName "COOP [8-12] - Crame le générateur"
 m_sAuthor "tanin69"
 m_sDescription "Mener une opération de sabotage en territoire ennemi et s'exfiltrer, le tout en préservant les effectifs"
 m_sIcon "{030E2E704B1974C2}UI/Textures/EditorPreviews/Characters/OPFOR/USSR_Army/Character_USSR_GL.edds"
 m_sLoadingScreen "{981489C7B8E7BF1C}UI/MissionLoadingScreens/FIA_Camp.edds"
 m_sGameMode "#AR-ServerBrower_ServerScenario"
 m_iPlayerCount 12
}