SCR_MissionHeader {
 World "{3175CD6DD72E1F91}worlds/tanin69/Marsoc_01.ent"
 m_sName "COOP (15-22) - Au charbon"
 m_sAuthor "tanin69"
 m_sDescription "IL fait noir, si noir..."
 m_sDetails "Libération de prisonniers par des FS sous contrainte de temps"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sLoadingScreen "{9074096D4EF401B9}UI/MissionLoadingScreens/huey_1.edds"
 m_sGameMode "#AR-ServerBrower_ServerScenario"
 m_iPlayerCount 30
 m_iMapMarkerLimitPerPlayer 20
}