SCR_MissionHeader {
 World "{4615E32C33B99EC4}worlds/tanin69/plus_grave.ent"
 m_sName "COOP (20-30) - C'est plus grave"
 m_sAuthor "tanin69"
 m_sDescription "Un si beau petit village..."
 m_sDetails "Libérer et tenir. Infanterie avec soutien UH-1."
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sLoadingScreen "{9074096D4EF401B9}UI/MissionLoadingScreens/huey_1.edds"
 m_sGameMode "#AR-ServerBrower_ServerScenario"
 m_iPlayerCount 30
 m_iMapMarkerLimitPerPlayer 20
}