SCR_MissionHeader {
 World "{0876A28E781EC0A7}worlds/tanin69/Simply City.ent"
 m_sName "COOP (20-30) - Simply City"
 m_sAuthor "tanin69"
 m_sDescription "Vanille à la fraise. Serez vous la vanille, ou le coulis de fraise ?"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sLoadingScreen "{FD88F7ED25F37D1B}UI/MissionLoadingScreens/BTR-70-firing_FIA.edds"
 m_sGameMode "#AR-ServerBrower_ServerScenario"
 m_iPlayerCount 30
 m_iMapMarkerLimitPerPlayer 20
}