SCR_MissionHeader {
 World "{F03AAEC91B8C1DBB}worlds/tanin69/Mission_03.ent"
 m_sName "COOP (10-...) - Nid de frelons"
 m_sAuthor "tanin69"
 m_sDescription "Localiser et détruite des armes lourdes."
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sLoadingScreen "{981489C7B8E7BF1C}UI/MissionLoadingScreens/FIA_Camp.edds"
 m_sGameMode "#AR-ServerBrower_ServerScenario"
 m_iPlayerCount 29
}