SCR_MissionHeader {
 World "{960E31E3C41D1E4B}worlds/tanin69/Mission_02.ent"
 m_sName "COOP (10-29) - Mal ambushé"
 m_sAuthor "tanin69"
 m_sDescription "Empêcher un sabotage par une force paramilitaire. Votre pays, la République du Peuple de Zimnitrita doit se défendre contre les intérêts étrangers."
 m_sIcon "{030E2E704B1974C2}UI/Textures/EditorPreviews/Characters/OPFOR/USSR_Army/Character_USSR_GL.edds"
 m_sLoadingScreen "{FD88F7ED25F37D1B}UI/MissionLoadingScreens/BTR-70-firing_FIA.edds"
 m_sGameMode "#AR-ServerBrower_ServerScenario"
 m_iPlayerCount 29
}