SCR_MissionHeader {
 World "{327520439BF6D341}worlds/tanin69/Mission_02b.ent"
 m_sName "COOP (10-...) - Papers please"
 m_sAuthor "tanin69"
 m_sDescription "Neutrilser des terroristes dits \"paramlitaires\" concentrés sur un village. Récupérer des preuves de l'intervention US dans le conflit."
 m_sDetails "Tu veux des détails ? Tu en auras en temps voulu, mec !"
 m_sIcon "{030E2E704B1974C2}UI/Textures/EditorPreviews/Characters/OPFOR/USSR_Army/Character_USSR_GL.edds"
 m_sLoadingScreen "{FD88F7ED25F37D1B}UI/MissionLoadingScreens/BTR-70-firing_FIA.edds"
 m_sGameMode "#AR-ServerBrower_ServerScenario"
 m_iPlayerCount 27
}