SCR_MissionHeader {
 World "{F03AAEC91B8C1DBB}worlds/tanin69/Mission_03.ent"
 m_sName "COOP (10-...) - Nid de frelons"
 m_sAuthor "tanin69"
 m_sDescription "Localiser et détruite des armes lourdes."
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sLoadingScreen "{A539259D33B8ED82}UI/MissionLoadingScreens/Loading_screen_Mission-03.edds"
 m_sGameMode "#AR-ServerBrower_ServerScenario"
 m_iPlayerCount 29
}