WeatherStateMachine {
 States {
  SCR_WeatherState "{5554DA5A67ACC7E5}" {
   Transitions {
    WeatherTransition "{5554DA5A8C012764}" {
     TransitionDurationHoursMin 0.25
     TransitionDurationHoursMax 0.5
    }
   }
   StateDurationHoursMin 0.25
   StateDurationHoursMax 0.5
   WeatherVariant0 WeatherVariant "{555888011627D6AF}" {
    VariantTransitions {
     WeatherTransition "{5554F043A2CEEF8B}" {
      TransitionDurationHoursMin 0.25
      TransitionDurationHoursMax 0.5
     }
    }
    DurationMin 0.25
    DurationMax 0.5
   }
  }
  SCR_WeatherState "{5556710B6B2315D0}" {
   Transitions {
    WeatherTransition "{5556804C64BFAC16}" {
     TransitionDurationHoursMin 0.25
     TransitionDurationHoursMax 0.5
    }
    WeatherTransition "{5556804C71478FEE}" {
     TransitionDurationHoursMin 0.25
     TransitionDurationHoursMax 0.5
    }
   }
   StateDurationHoursMin 0.167
   StateDurationHoursMax 0.5
   WeatherVariant0 WeatherVariant "{56248BCDA03159B3}" {
    RainPattern WeatherRainPattern "{5588AC8D6DA8EA04}" {
     RainDurationMin 0.25
     RainDurationMax 0.5
    }
    VariantTransitions {
     WeatherTransition "{555684EFFDED414B}" {
      TransitionDurationHoursMin 0.25
      TransitionDurationHoursMax 0.5
     }
    }
    DurationMin 0.25
    DurationMax 0.5
   }
  }
  SCR_WeatherState "{55568B9A09118BA8}" {
   Transitions {
    WeatherTransition "{55568B9A04F7BAB3}" {
     TransitionDurationHoursMin 0.25
     TransitionDurationHoursMax 0.5
    }
    WeatherTransition "{55568B9A14EFAB52}" {
     TransitionDurationHoursMin 0.25
     TransitionDurationHoursMax 0.333
    }
   }
   StateDurationHoursMin 0.25
   StateDurationHoursMax 0.5
   WeatherVariant0 WeatherVariant "{56248BCDA0315911}" {
    VariantTransitions {
     WeatherTransition "{55568B9CF085CFC4}" {
      TransitionDurationHoursMin 0.25
      TransitionDurationHoursMax 0.5
     }
    }
    DurationMin 0.25
    DurationMax 0.5
   }
  }
  SCR_WeatherState "{5556B626F7F40452}" {
   Transitions {
    WeatherTransition "{5556B62702F0E391}" {
     TransitionDurationHoursMin 0.25
     TransitionDurationHoursMax 0.5
    }
    WeatherTransition "{5556B6271C544EB4}" {
     TransitionDurationHoursMin 0.25
     TransitionDurationHoursMax 0.5
    }
   }
   StateDurationHoursMin 0.25
   StateDurationHoursMax 0.5
   WeatherVariant0 WeatherVariant "{55588801387B7AC2}" {
    VariantTransitions {
     WeatherTransition "{5556B627F50DFBC2}" {
      TransitionDurationHoursMin 0.25
      TransitionDurationHoursMax 0.5
     }
    }
    DurationMin 0.25
    DurationMax 0.5
   }
  }
 }
}